// license-header java merge-point
/* Autogenerated on 04/28/2016 01:20:56-0400 by AndroMDA
 *
 * TEMPLATE:    jaxws/WebServiceDelegate.vsl in andromda-webservices-cartridge
 * MODEL CLASS: AndroMDAModel::org.sw.andromda.lastrest::service::SearchService
 * STEREOTYPE:  Service
 * STEREOTYPE:  WebService
*/
package org.sw.andromda.lastrest.service;

import java.util.List;
import org.sw.andromda.lastrest.vo.DocumentVO;
import org.sw.andromda.lastrest.vo.SearchResultVO;

//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;

/**
 * WebService Service Endpoint Implementation delegate for the SearchService service.
 * 
 */

public class SearchServiceWSDelegate
{
   // private static final Logger LOG = LoggerFactory.getLogger(SearchServiceWSDelegate.class);
   // private static final String className = "SearchServiceWSDelegate";

    /**
     * Constructor
     */
    public SearchServiceWSDelegate()
    {
        //Documented empty code block - avoid compiler warning
    }

   /**
    * Invokes the indexDocument service method on SearchService.
    * 
    * @param documents DocumentVO multiplicity=0..-1
    * @return indexDocumentResponse Boolean
    */
    public Boolean indexDocument
    (
        List<DocumentVO> documents
    )
    {
        // Populate method wrapper object so all parameters can be logged and transformed at once
        // Transform input parameters to domain request object
        /*Boolean rtn =*/ IndexDocumentImpl.indexDocumentTransformInput(
            documents
        );

        //TODO: Implement service operation
        //throw new UnsupportedOperationException("Service SearchService.indexDocument not implemented.");
        // Dummy return value implementation with default values, modify Impl class.
        Boolean rtn = IndexDocumentImpl.indexDocumentTransformResponse(/* Domain response to be transformed to service response */);
        return rtn;
    }

   /**
    * Invokes the performSearch service method on SearchService.
    * 
    * @param queryTerm datatype String multiplicity=1..1
    * @return performSearchResponse SearchResultVO
    */
    public SearchResultVO performSearch
    (
        String queryTerm
    )
    {
        // Populate method wrapper object so all parameters can be logged and transformed at once
        // Transform input parameters to domain request object
        /*SearchResultVO rtn =*/ PerformSearchImpl.performSearchTransformInput(
            queryTerm
        );

        //TODO: Implement service operation
        //throw new UnsupportedOperationException("Service SearchService.performSearch not implemented.");
        // Dummy return value implementation with default values, modify Impl class.
        SearchResultVO rtn = PerformSearchImpl.performSearchTransformResponse(/* Domain response to be transformed to service response */);
        return rtn;
    }
}