// license-header java merge-point
/* Autogenerated on 04/28/2016 01:20:56-0400 by AndroMDA
 *
 * TEMPLATE:    jaxws/WebServiceSEIImplTest.vsl in andromda-webservices-cartridge
 * MODEL CLASS: AndroMDAModel::org.sw.andromda.lastrest::service::SearchService
 * STEREOTYPE:  Service
 * STEREOTYPE:  WebService
*/
package org.sw.andromda.lastrest.service;

import junit.framework.TestCase;
import junit.textui.TestRunner;
import org.sw.andromda.lastrest.vo.SearchResultVO;

/**
 * WebService Service Delegate Test for the SearchService service.
 * 
 */

public class SearchServiceSEIImplTest extends TestCase
{
    /**
     * Constructor
     * @param name test case name
     */
    public SearchServiceSEIImplTest(String name)
    {
        super(name);
    }

    /**
     * No arg Constructor. Delegates to constructor(String) with test case name
     */
    public SearchServiceSEIImplTest()
    {
        super("SearchService");
    }

    /**
     * @see junit.framework.TestCase#setUp()
     */
    @Override
    protected void setUp() throws Exception
    {
        super.setUp();
    }

    /**
     * @see junit.framework.TestCase#tearDown()
     */
    @Override
    protected void tearDown() throws Exception
    {
        super.tearDown();
    }

    /**
     * Test method for {@link org.sw.andromda.lastrest.service.SearchServiceSEIImpl#SearchServiceSEIImpl()}.
     */
    public void testSearchServiceSEIImplIndexDocument()
    {
        // TestCase.setUp and tearDown methods for each individual service method test
        IndexDocumentImpl.indexDocumentSetUp();
        IndexDocument indexDocumentInput = IndexDocumentImpl.indexDocumentCreateInput();
        SearchServiceSEIImpl delegate = new SearchServiceSEIImpl();
        System.out.println("Invoking SearchServiceSEIImpl.indexDocument with " + indexDocumentInput);
            Boolean rtn = delegate.indexDocument(
             indexDocumentInput.getDocuments()  // java.util.Set<org.sw.andromda.lastrest.vo.DocumentVO>
        );
        System.out.println("SearchServiceSEIImpl.indexDocument" + " returned " + rtn);
        IndexDocumentImpl.indexDocumentTearDown();
    }

    /**
     * Test method for {@link org.sw.andromda.lastrest.service.SearchServiceSEIImpl#SearchServiceSEIImpl()}.
     */
    public void testSearchServiceSEIImplPerformSearch()
    {
        // TestCase.setUp and tearDown methods for each individual service method test
        PerformSearchImpl.performSearchSetUp();
        PerformSearch performSearchInput = PerformSearchImpl.performSearchCreateInput();
        SearchServiceSEIImpl delegate = new SearchServiceSEIImpl();
        System.out.println("Invoking SearchServiceSEIImpl.performSearch with " + performSearchInput);
            SearchResultVO rtn = delegate.performSearch(
             performSearchInput.getQueryTerm()  // java.lang.String
        );
        System.out.println("SearchServiceSEIImpl.performSearch" + " returned " + rtn);
        PerformSearchImpl.performSearchTearDown();
    }

    /**
     * main() method to run the test with the textual test runner.
     * @param args Not used
     */
    public static void main(final String[] args)
    {
        TestRunner.run(SearchServiceSEIImplTest.class);
    }
}