// license-header java merge-point
/* Autogenerated on 04/28/2016 01:20:56-0400 by AndroMDA DO NOT EDIT!
 *
 * TEMPLATE:    cxf/WSClient.vsl in andromda-webservices-cartridge
 * MODEL CLASS: AndroMDAModel::org.sw.andromda.lastrest::service::SearchService
 * STEREOTYPE:  Service
 * STEREOTYPE:  WebService
*/
package org.sw.andromda.lastrest.service.test;

import java.net.URL;
import javax.xml.namespace.QName;
import junit.framework.TestCase;
import junit.textui.TestRunner;
import org.sw.andromda.lastrest.service.IndexDocument;
import org.sw.andromda.lastrest.service.IndexDocumentImpl;
import org.sw.andromda.lastrest.service.PerformSearch;
import org.sw.andromda.lastrest.service.PerformSearchImpl;
import org.sw.andromda.lastrest.service.SearchServiceSEI;
import org.sw.andromda.lastrest.service.SearchServiceSEIClient;
import org.sw.andromda.lastrest.vo.DocumentVO;
import org.sw.andromda.lastrest.vo.SearchResultVO;

/**
 * Client test for the SearchService web service. Modified from CXF generated test client.
 * 
 */
public final class SearchService_WSClient extends TestCase
{
    private static final QName SERVICE_NAME = new QName("http://service.lastrest.andromda.sw.org/", "SearchService");
    private static URL wsdlURL = null;

    /**
     * Public constructor for JUnit
     */
    public SearchService_WSClient()
    {
        // Documented empty constructor - avoid compiler warning
    }

    /**
     * @param name
     */
    public SearchService_WSClient(String name)
    {
        super(name);
    }

    /**
     * @see junit.framework.TestCase#setUp()
     */
    @Override
    protected void setUp() throws Exception
    {
        super.setUp();
        //if (args.length == 0)
        //{
            wsdlURL = SearchServiceSEIClient.WSDL_LOCATION;
        //}
        /*else
        {
            File wsdlFile = new File(args[0]);
            try
            {
                if (wsdlFile.exists())
                {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else
                {
                    wsdlURL = new URL(args[0]);
                }
            }
            catch (MalformedURLException e)
            {
                e.printStackTrace();
            }
        } */
    }

    /**
     * @see junit.framework.TestCase#tearDown()
     */
    @Override
    protected void tearDown() throws Exception
    {
        super.tearDown();
    }

    /**
     * @param args
     * @throws Exception
     */
    public static void main(String args[]) throws Exception
    {
        TestRunner.run(SearchService_WSClient.class);

        /*

       //  Boolean _indexDocument__return =           testIndexDocument(port);

       //  SearchResultVO _performSearch__return =           testPerformSearch(port);
       */
    }
    /**
     * Test SearchService Service indexDocument
     */
    public void testIndexDocument()
    {
        IndexDocument indexDocumentInput = IndexDocumentImpl.indexDocumentCreateInput();
        System.out.println("Invoking indexDocument on SearchService with"
            + " documents=" + indexDocumentInput.getDocuments()
        );
        SearchServiceSEIClient ss = new SearchServiceSEIClient(wsdlURL, SERVICE_NAME);
        SearchServiceSEI port = ss.getSearchService();
        Boolean _indexDocument__return = port.indexDocument(
             indexDocumentInput.getDocuments()
        );
        System.out.println("indexDocument.result=" + _indexDocument__return);
        // return _indexDocument__return;
    }

    /**
     * Test SearchService Service performSearch
     */
    public void testPerformSearch()
    {
        PerformSearch performSearchInput = PerformSearchImpl.performSearchCreateInput();
        System.out.println("Invoking performSearch on SearchService with"
            + " queryTerm=" + performSearchInput.getQueryTerm()
        );
        SearchServiceSEIClient ss = new SearchServiceSEIClient(wsdlURL, SERVICE_NAME);
        SearchServiceSEI port = ss.getSearchService();
        SearchResultVO _performSearch__return = port.performSearch(
             performSearchInput.getQueryTerm()
        );
        System.out.println("performSearch.result=" + _performSearch__return);
        // return _performSearch__return;
    }

    /**
     * JUnit test data class, used by DataDrivenTestSuite in suite()
     */
    public static class SearchServiceTestData
    {
        // TODO: Add test data fields here (populated by SearchService.xls spreadsheet
        // TODO: Recursively list every primitive parameter in entire operation parameter hierarchy
        @SuppressWarnings("unused")
        private DocumentVO indexDocumentDocuments;
        /**
         * Data value for documents indexDocument on used by DataDrivenTestSuite in suite().
         * indexDocumentdocuments must be the column name of the parameter in the spreadsheet
         * @param value DocumentVO to be populated manually
         */
        public void setIndexDocumentDocuments(DocumentVO value)
        {
            this.indexDocumentDocuments = value;
        }
        @SuppressWarnings("unused")
        private String performSearchQueryTerm;
        /**
         * Data value for queryTerm performSearch on used by DataDrivenTestSuite in suite().
         * performSearchqueryTerm must be the column name of the parameter in the spreadsheet
         * @param value String to be populated manually
         */
        public void setPerformSearchQueryTerm(String value)
        {
            this.performSearchQueryTerm = value;
        }
    }
}